In [2]:
import pandas as pd

In [3]:
df_sales_summary_report =pd.read_excel('../data/processed/IPSalesSummaryReport.xlsx')

In [4]:
df_sales_summary_report.head()

,Unnamed: 0,Registrationno,Ipid,Patient Name,Bill No,Bill Amount,Discount,DoctorName,Discount.1,AdmitDatetime,...,Diet Counselling,Food and Beverages,GST 5 % on Room Rent,PackageFees,Package Name,Test,Doctor Specialisation,Diagnosis,Category,Company
0,0,101,1001,PN1,BILL0001,2812322,0.0,RAJU SV,ANAESTHESIOLOGY & PAIN MANAGEMENT,2021-03-28 11:38:09,...,0.0,175230.0,0.0,0.0,NaN,STAGE I,ORTHOPAEDICS,MEDICAL,MOH-ZANZIBAR & SEYCHELLES,MINISTRY OF HEALTH ZANZIBAR TANZANIA
1,1,102,1002,PN2,BILL0002,2009122,0.0,RAJU SV,ANAESTHESIOLOGY & PAIN MANAGEMENT,2021-04-16 10:15:40,...,0.0,138400.0,0.0,0.0,NaN,EXTENDED,GENERAL SURGERY,MEDICAL,MOH-ZANZIBAR & SEYCHELLES,MINISTRY OF HEALTH ZANZIBAR TANZANIA
2,2,103,1003,PN3,BILL0003,1043624,0.0,RAJU SV,ANAESTHESIOLOGY & PAIN MANAGEMENT,2021-04-23 10:37:16,...,0.0,137970.0,0.0,0.0,NaN,NaN,NaN,MEDICAL,MOH-ZANZIBAR & SEYCHELLES,MINISTRY OF HEALTH ZANZIBAR TANZANIA
3,3,104,1004,PN4,BILL0004,1405912,0.0,RAJU SV,ANAESTHESIOLOGY & PAIN MANAGEMENT,2021-04-27 09:51:10,...,0.0,204215.0,0.0,0.0,NaN,NaN,NaN,MEDICAL,SIMSINT,SIMS INT
4,4,105,1005,PN5,BILL0005,2477740,208237.0,VIJAYALAKSHMI BALAKRISHNAN,INFECTIOUS DISEASES,2021-05-23 19:30:55,...,0.0,2685.0,0.0,0.0,NaN,NaN,NaN,MEDICAL,SIMS,MEDI ASSIST INDIA TPA PVT.LTD

In [5]:
df_sales_summary_report['Package Name'].isna().sum()

847

In [6]:
df_sales_summary_report['Test'].isna().sum()

516

In [7]:
df_sales_summary_report=df_sales_summary_report.drop(['Unnamed: 0'],axis =1)

In [8]:
df_sales_summary_report.head()

,Registrationno,Ipid,Patient Name,Bill No,Bill Amount,Discount,DoctorName,Discount.1,AdmitDatetime,DischargeDatetime,...,Diet Counselling,Food and Beverages,GST 5 % on Room Rent,PackageFees,Package Name,Test,Doctor Specialisation,Diagnosis,Category,Company
0,101,1001,PN1,BILL0001,2812322,0.0,RAJU SV,ANAESTHESIOLOGY & PAIN MANAGEMENT,2021-03-28 11:38:09,2021-07-29 22:50:42.487000,...,0.0,175230.0,0.0,0.0,NaN,STAGE I,ORTHOPAEDICS,MEDICAL,MOH-ZANZIBAR & SEYCHELLES,MINISTRY OF HEALTH ZANZIBAR TANZANIA
1,102,1002,PN2,BILL0002,2009122,0.0,RAJU SV,ANAESTHESIOLOGY & PAIN MANAGEMENT,2021-04-16 10:15:40,2021-07-29 22:53:00.127000,...,0.0,138400.0,0.0,0.0,NaN,EXTENDED,GENERAL SURGERY,MEDICAL,MOH-ZANZIBAR & SEYCHELLES,MINISTRY OF HEALTH ZANZIBAR TANZANIA
2,103,1003,PN3,BILL0003,1043624,0.0,RAJU SV,ANAESTHESIOLOGY & PAIN MANAGEMENT,2021-04-23 10:37:16,2021-07-29 22:54:49.377000,...,0.0,137970.0,0.0,0.0,NaN,NaN,NaN,MEDICAL,MOH-ZANZIBAR & SEYCHELLES,MINISTRY OF HEALTH ZANZIBAR TANZANIA
3,104,1004,PN4,BILL0004,1405912,0.0,RAJU SV,ANAESTHESIOLOGY & PAIN MANAGEMENT,2021-04-27 09:51:10,2021-08-04 14:43:10.463000,...,0.0,204215.0,0.0,0.0,NaN,NaN,NaN,MEDICAL,SIMSINT,SIMS INT
4,105,1005,PN5,BILL0005,2477740,208237.0,VIJAYALAKSHMI BALAKRISHNAN,INFECTIOUS DISEASES,2021-05-23 19:30:55,2021-07-09 15:10:22.933000,...,0.0,2685.0,0.0,0.0,NaN,NaN,NaN,MEDICAL,SIMS,MEDI ASSIST INDIA TPA PVT.LTD

In [9]:
df_sales_summary_report.describe()

,Registrationno,Ipid,Bill Amount,Discount,Room Rent,Nursing Charges,DMO,Laundry Charges,Medical Service and Monitor Charges,PPE Masks Other Bedside Consumables,...,ICCU Consumables,Implants.1,Professional Treatment Chagres,Bedside Procedure,Surgeries.2,Room Occupancy,Diet Counselling,Food and Beverages,GST 5 % on Room Rent,PackageFees
count,999.000000,999.000000,9.990000e+02,999.000000,999.000000,999.000000,999.000000,999.000000,999.000000,999.000000,...,998.0,998.0,998.0,998.0,998.0,998.000000,998.0,998.000000,998.0,9.980000e+02
mean,510.010010,1500.000000,2.673197e+05,9201.524325,31548.516016,3067.317317,3970.365365,1.051051,187.187187,334.834835,...,0.0,0.0,0.0,0.0,0.0,1109.218437,0.0,1243.271543,0.0,2.192984e+04
std,274.123489,288.530761,3.835628e+05,31855.197722,67684.060619,5195.279084,7146.567994,33.220530,3122.498357,5541.991979,...,0.0,0.0,0.0,0.0,0.0,6330.009558,0.0,10560.609317,0.0,1.312610e+05
min,101.000000,1001.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000e+00
25%,250.500000,1250.500000,5.757700e+04,0.000000,2812.500000,350.000000,450.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000e+00
50%,500.000000,1500.000000,1.482550e+05,0.000000,13000.000000,1400.000000,1800.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,50.000000,0.0,0.000000e+00
75%,749.500000,1749.500000,3.189160e+05,6217.500000,34000.000000,3875.000000,4650.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,603.750000,0.0,0.000000e+00
max,999.000000,1999.000000,3.548475e+06,499079.000000,805750.000000,59400.000000,79200.000000,1050.000000,78000.000000,138000.000000,...,0.0,0.0,0.0,0.0,0.0,94500.000000,0.0,204215.000000,0.0,2.200000e+06

In [16]:
null_list =[]
for i in df_sales_summary_report.select_dtypes('number').columns:
    if (df_sales_summary_report[i].sum()==0):
        null_list .append(i)

In [18]:
df_sales_summary_new = df_sales_summary_report.drop(null_list,axis=1)

In [19]:
df_sales_summary_new.head()

,Registrationno,Ipid,Patient Name,Bill No,Bill Amount,Discount,DoctorName,Discount.1,AdmitDatetime,DischargeDatetime,...,Miscellaneous,Room Occupancy,Food and Beverages,PackageFees,Package Name,Test,Doctor Specialisation,Diagnosis,Category,Company
0,101,1001,PN1,BILL0001,2812322,0.0,RAJU SV,ANAESTHESIOLOGY & PAIN MANAGEMENT,2021-03-28 11:38:09,2021-07-29 22:50:42.487000,...,23922.0,9750.0,175230.0,0.0,NaN,STAGE I,ORTHOPAEDICS,MEDICAL,MOH-ZANZIBAR & SEYCHELLES,MINISTRY OF HEALTH ZANZIBAR TANZANIA
1,102,1002,PN2,BILL0002,2009122,0.0,RAJU SV,ANAESTHESIOLOGY & PAIN MANAGEMENT,2021-04-16 10:15:40,2021-07-29 22:53:00.127000,...,1608.0,13000.0,138400.0,0.0,NaN,EXTENDED,GENERAL SURGERY,MEDICAL,MOH-ZANZIBAR & SEYCHELLES,MINISTRY OF HEALTH ZANZIBAR TANZANIA
2,103,1003,PN3,BILL0003,1043624,0.0,RAJU SV,ANAESTHESIOLOGY & PAIN MANAGEMENT,2021-04-23 10:37:16,2021-07-29 22:54:49.377000,...,1125.0,0.0,137970.0,0.0,NaN,NaN,NaN,MEDICAL,MOH-ZANZIBAR & SEYCHELLES,MINISTRY OF HEALTH ZANZIBAR TANZANIA
3,104,1004,PN4,BILL0004,1405912,0.0,RAJU SV,ANAESTHESIOLOGY & PAIN MANAGEMENT,2021-04-27 09:51:10,2021-08-04 14:43:10.463000,...,5095.0,0.0,204215.0,0.0,NaN,NaN,NaN,MEDICAL,SIMSINT,SIMS INT
4,105,1005,PN5,BILL0005,2477740,208237.0,VIJAYALAKSHMI BALAKRISHNAN,INFECTIOUS DISEASES,2021-05-23 19:30:55,2021-07-09 15:10:22.933000,...,8017.0,0.0,2685.0,0.0,NaN,NaN,NaN,MEDICAL,SIMS,MEDI ASSIST INDIA TPA PVT.LTD

In [20]:
df_sales_summary_new.to_excel('../data/final/Ip_Sales_Summary_Report_Final.xlsx')